name: Make docker image

on:
  push: 
    branches: "master" 
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: WebAppDocker


    steps:
      - uses: actions/checkout@v3
      - name: Build the docker image
        run: docker build . --file "${{ env.PROJECT_PATH }}/Dockerfile" --tag webappdocker:$(date +%s)
        
