name: Publish docker container to heroku
on: 
  push: 
    branches: [ master ]
    paths-ignore:
      - '**/*.md'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'webappdocker' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Publish
        run: | 
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
