name: Publish docker container to heroku
on: 
  push: 
    branches: [ master ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: docker login --username=${{ secrets.HEROKU_EMAIL}} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Publish
        run: | 
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
